# Numpy

In [2]:
import numpy as np

In [18]:
def print_obj(obj, name):
    print("%s: \n%s\n" % (name, obj))

def check_each(a, b):
    return (a == b).astype('bool')

def check_mean(a, b):
    return np.mean(a == b).astype('bool')

In [19]:
a = np.array(1.)
b = np.array([1., 2., 3.])
c = np.array([[1., 2., 3.], [4., 5., 6.]])

In [20]:
print_obj(a, 'a')
print_obj(a.ndim, 'a.ndim')
print_obj(c.ndim, 'c.ndim')
print_obj(c.shape, 'c.shape')

a: 
1.0

a.ndim: 
0

c.ndim: 
2

c.shape: 
(2, 3)



In [25]:
d = np.array([[[1., 2., 3], [4., 5., 6.,]], [[7., 8., 9.,], [10., 11., 12]]])
e = np.array([[[1, 2, 3, 4]], [[5, 6, 7, 8]]])


In [26]:
print_obj(d, 'd')
print_obj(d.ndim, 'd.ndim')
print_obj(d.shape, 'd.shape')

d: 
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]

d.ndim: 
3

d.shape: 
(2, 2, 3)



In [27]:
print_obj(e, 'e')
print_obj(e.ndim, 'e.ndim')
print_obj(e.shape, 'e.shape')   # shape: 밖에서부터 안쪽으로 들어옴

e: 
[[[1 2 3 4]]

 [[5 6 7 8]]]

e.ndim: 
3

e.shape: 
(2, 1, 4)



In [29]:
a = np.ones(10)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [33]:
a = np.zeros((3, 4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [38]:
a = np.full((3, 5), 7)   # 첫 번째 인자: decides SHAPE of matrix
                         # 두 번째 인자: the NUMBER that will go in to spaces
                         
a

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [48]:
a = np.random.random((2, 3, 4))
a

array([[[0.48355114, 0.43653739, 0.17226677, 0.01260964],
        [0.57471239, 0.7376216 , 0.5097043 , 0.97530743],
        [0.19253243, 0.85712367, 0.66700361, 0.07775156]],

       [[0.34077866, 0.28846376, 0.99326642, 0.7923597 ],
        [0.94536493, 0.0720574 , 0.19379607, 0.5633327 ],
        [0.14708962, 0.71779335, 0.82093984, 0.25409311]]])

In [49]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
a = np.arange(10).astype(float)
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [51]:
a = np.arange(10).reshape(5, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [55]:
# quiz
a = np.arange(24).astype(float).reshape(4, 3, 2)
a

array([[[ 0.,  1.],
        [ 2.,  3.],
        [ 4.,  5.]],

       [[ 6.,  7.],
        [ 8.,  9.],
        [10., 11.]],

       [[12., 13.],
        [14., 15.],
        [16., 17.]],

       [[18., 19.],
        [20., 21.],
        [22., 23.]]])

In [56]:
a = np.arange(10)

In [67]:
print(a[:])
print(a[-4:])
print(a[:-8])

print(a[0:10:2])     # start : end : step
print(a[::-1])
print(a[8:5:-1])

# quiz
print(a[:2:-3])

[0 1 2 3 4 5 6 7 8 9]
[6 7 8 9]
[0 1]
[0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0]
[8 7 6]
[9 6 3]


In [92]:
# indexing a matrix
a = np.arange(9).reshape(3,3)

print(a[:][-1])
print(a[1:, 2])

[6 7 8]
[5 8]


In [106]:
# indexing and slicing a 3D tensor
a = np.arange(4*3*2).reshape((4, 3, 2))
print(a, end='\n\n')

# print(a[0], end='\n\n')
# print(a[0, 1], end='\n\n')
print(a[:2, :, 0])

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]

[[ 0  2  4]
 [ 6  8 10]]


In [110]:
# conditional index
a = np.arange(3*2).reshape((3,2))
print(a, end='\n\n')

idx = a % 2 == 0
print(idx, end='\n\n')

print(a[a>=3])

[[0 1]
 [2 3]
 [4 5]]

[[ True False]
 [ True False]
 [ True False]]

[3 4 5]


In [113]:
a = np.arange(2*4).reshape((2, 4))
print(a, end='\n\n')

idx = ((0, 1, 0, 1), (0, 1, 2, 3))
print(a[idx])
print(a[(0, 1, 0, 1), (0, 1, 2, 3)])

[[0 1 2 3]
 [4 5 6 7]]

[0 5 2 7]
[0 5 2 7]


In [120]:
idx = np.array([[1, 0], [1, 1]])
a[idx]

array([[[4, 5, 6, 7],
        [0, 1, 2, 3]],

       [[4, 5, 6, 7],
        [4, 5, 6, 7]]])

In [125]:
a = np.arange(6).reshape((3, 2))
b = np.ones((2, 3))

print(a, end='\n\n')
print(b, end='\n\n')

print(np.dot(a, b), end='\n\n')
print(a@b, end='\n\n')
print(np.matmul(a, b))

[[0 1]
 [2 3]
 [4 5]]

[[1. 1. 1.]
 [1. 1. 1.]]

[[1. 1. 1.]
 [5. 5. 5.]
 [9. 9. 9.]]

[[1. 1. 1.]
 [5. 5. 5.]
 [9. 9. 9.]]

[[1. 1. 1.]
 [5. 5. 5.]
 [9. 9. 9.]]


In [129]:
a = np.arange(12).reshape((2,3,2))
print(a, end='\n\n')

b = a.reshape(6, -1)    # -1 in reshape does the calculation for me
print(b, end='\n\n')

b = a.reshape((-1, 2, 2))
print(b, end='\n\n')

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]



In [130]:
# adding an extra dimension to a matrix
a = np.arange(3)
print(a, end='\n\n')

print(a[:, None])

[0 1 2]

[[0]
 [1]
 [2]]


In [138]:
a = np.ones((3, 2))
b = np.zeros((3, 2))

print(a, end='\n\n')
print(b, end='\n\n')

# print(np.vstack([a, b]), end='\n\n')
# print(np.hstack([a, b]), end='\n\n')
# print(np.hstack([a, b, a]), end='\n\n')

print(np.concatenate([a, b], axis=0), end='\n\n')
print(np.concatenate([a, b], axis=1))

[[1. 1.]
 [1. 1.]
 [1. 1.]]

[[0. 0.]
 [0. 0.]
 [0. 0.]]

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

[[1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]]


In [139]:
a = np.arange(24).reshape((4, 3, 2))
print(a, end='\n\n')

b = np.transpose(a, [0, 2, 1])
print(b, end='\n\n')

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]

[[[ 0  2  4]
  [ 1  3  5]]

 [[ 6  8 10]
  [ 7  9 11]]

 [[12 14 16]
  [13 15 17]]

 [[18 20 22]
  [19 21 23]]]



In [140]:
c = np.transpose(a, [1, 0, 2])
c

array([[[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19]],

       [[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21]],

       [[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23]]])

In [141]:
# broadcasting
# even if shape of matrices don't match, numpy matches the shape via broadcasting

In [142]:
def sigmoid(x):
    return 1. / (1. + np.exp(-x))

def foo(M, W):
    return 0

In [174]:
def M(m, n):
    a = np.arange(m*n).reshape((m, n))
    print(a, end='\n\n')

    m_half = round(m/2)

    b = a[:m_half]
    print(b, end='\n\n')
    c = a[m_half:]
    print(c, end='\n\n')

    d = a[1: :2]
    print(d, end='\n\n')
    e = a[0: :2]
    print(e, end='\n\n')

    X = np.concatenate([b, c, d, e], axis=1)
    print(X, end='\n\n')
    print(X.shape, end='\n\n')

    def W(n):
        f = np.arange(4*n*n).reshape((4*n, n))
        return f
    
    g = np.sum(X.mean(axis=0))
    print(g, end='\n\n')

In [173]:
M(4, 2)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]

[[0 1]
 [2 3]]

[[4 5]
 [6 7]]

[[2 3]
 [6 7]]

[[0 1]
 [4 5]]

[[0 1 4 5 2 3 0 1]
 [2 3 6 7 6 7 4 5]]

(2, 8)

28.0

